### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by reach2rv** [dranger003/WTSPlugin1#1]
Hi,

I need you support for getting this project ahead with file transfer facility. I am open to discuss on how we can work together.

Kindly write me reach2rv-@-gmail-com

**Comment by patv2learn** [comment]
Hello reach2rv, are you able to make this work? I am need of same kind of work but this program is not working.

**Comment by reach2rv** [comment]
Hi @patv2learn, 
I got this working with some changes. I can share code with a small favor of help to complete the project as I also need to for some work :)

**Comment by patv2learn** [comment]
Thanks reach2rv, I have try to debug more on this and getting Error #87 on following line.

`PInvoke.WriteFile(file, data, (uint)data.Length, out bytes, IntPtr.Zero)`

Basically in my project, I need to just pass text command both way which I am able to make it work using MSTSCLib control in c# but no success on default RDP. If anyway I can help you with anything I can surely try.

If you can update this project on github or send working copy on my email at patv2learn-@-gmail-com, that will be great help.

Thank you.
Pat

**Comment by reach2rv** [comment]
For just text command I need to check as my requirement was file transfer. I will look in to it by this weekend as I am traveling for next 3 days.

**Comment by patv2learn** [comment]
Thanks @reach2rv , in this code I got where the problem is but not sure how to fix this.

`PInvoke.WriteFile(file, data, (uint)data.Length, out bytes, IntPtr.Zero)`

Above line is supplying NULL for lpOverlapped (last) parameter and that's what is creating problem, it consider file pointer is created with FILE_FLAG_OVERLAPPED and so I have to supply OVERLAPPED but while supplying this, program immediately going on next line and that's where I am getting  ERROR_IO_PENDING error because WriteFile is not yet finished.

I am not sure how to get file pointer without FILE_FLAG_OVERLAPPED so WriteFile function can wait till task is finished when I have NULL supply there and that's what it should be.

If you have file transfer working, can you please update that and I can play more with that. If you are busy that's fine I am trying and if I get success I will update this github project else I will wait for you to come back.

Thanks again! TC.

**Comment by patv2learn** [comment]
Hello @dranger003, if you can suggest something on  above problem that would be great. Sorry, I am not C++ guy and not very good at API so this is giving nightmare to me.

**Comment by dranger003** [comment]
Hi, I updated the code but have not tested it. Let me know if that helps.

**Comment by patv2learn** [comment]
Thank you very much @dranger003, 

It is now giving error 997 (ERROR_IO_PENDING ) on WriteFile. 

Infect I have tried this change on my end today morning but after reading few help it looks like we can not supply NativeOverlapped, because that way it will be asynchronous while here we have to wait till write process got finished so best is we have to supply NULL.

Still, I am not sure if there is any other way around. I am trying to read more MSDN let's see if I get any workaround.

Thanks!

**Comment by dranger003** [comment]
Try this new update I just made. Tested OK here with a 1G file transfer. Ideally you would also need to update the ReadFile call to use overlapped I/O.

**Comment by patv2learn** [comment]
Thank you very much @dranger003, I will check this in little while and let you know if there is any problem.

I really appreciate your assistance on this issue.

**Comment by dranger003** [comment]
Glad if I can help.
